api {
    web_server: https://app.clear.ml
    api_server: https://api.clear.ml
    files_server: https://files.clear.ml
    credentials {
        access_key: ""
        secret_key: ""
    }
}

sdk {
    development {
        default_output_uri: "./clearml_artifacts"
        default_upload_destination: "files"
    }
}
